# Generated by Django 5.2.13 on 2026-04-14 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('current_stock', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
            ],
        ),
    ]
